
// This file has been generated by the GUI designer. Do not modify.
namespace Cheque.GTK.Screens
{
	public partial class CheckReport
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label lblName;
		private global::Gtk.Entry entryName;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label lbl_ID;
		private global::Gtk.Entry entryID;
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label lblStartDate;
		private global::Gtk.Entry entryStartDate;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label lblEndDate;
		private global::Gtk.Entry entryEndDate;
		private global::Gtk.HBox hbox9;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.VBox vbox7;
		private global::Gtk.HBox hbox10;
		private global::Gtk.Label lblBank;
		private global::Gtk.Entry entryBankNum;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Label lblBranchNum;
		private global::Gtk.Entry entryBranchNum;
		private global::Gtk.HBox hbox13;
		private global::Gtk.RadioButton radioBtnCashed;
		private global::Gtk.RadioButton radioBtnReturned;
		private global::Gtk.RadioButton radioBtnAll;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeview;
		private global::Gtk.Label lblTotal;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Cheque.GTK.Screens.CheckReport
			this.Name = "Cheque.GTK.Screens.CheckReport";
			this.Title = global::Mono.Unix.Catalog.GetString ("Relatório de Cheques");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 1024;
			this.DefaultHeight = 768;
			// Container child Cheque.GTK.Screens.CheckReport.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lblName = new global::Gtk.Label ();
			this.lblName.Name = "lblName";
			this.lblName.LabelProp = global::Mono.Unix.Catalog.GetString ("Nome:");
			this.hbox2.Add (this.lblName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entryName = new global::Gtk.Entry ();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.IsEditable = true;
			this.entryName.InvisibleChar = '●';
			this.hbox2.Add (this.entryName);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entryName]));
			w2.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lbl_ID = new global::Gtk.Label ();
			this.lbl_ID.Name = "lbl_ID";
			this.lbl_ID.LabelProp = global::Mono.Unix.Catalog.GetString ("CPF/CNPJ:");
			this.hbox3.Add (this.lbl_ID);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lbl_ID]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entryID = new global::Gtk.Entry ();
			this.entryID.CanFocus = true;
			this.entryID.Name = "entryID";
			this.entryID.IsEditable = true;
			this.entryID.InvisibleChar = '●';
			this.hbox3.Add (this.entryID);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entryID]));
			w5.Position = 1;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblStartDate = new global::Gtk.Label ();
			this.lblStartDate.Name = "lblStartDate";
			this.lblStartDate.LabelProp = global::Mono.Unix.Catalog.GetString ("Data de início:");
			this.hbox4.Add (this.lblStartDate);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblStartDate]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entryStartDate = new global::Gtk.Entry ();
			this.entryStartDate.CanFocus = true;
			this.entryStartDate.Name = "entryStartDate";
			this.entryStartDate.IsEditable = true;
			this.entryStartDate.InvisibleChar = '●';
			this.hbox4.Add (this.entryStartDate);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entryStartDate]));
			w8.Position = 1;
			this.vbox4.Add (this.hbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lblEndDate = new global::Gtk.Label ();
			this.lblEndDate.Name = "lblEndDate";
			this.lblEndDate.LabelProp = global::Mono.Unix.Catalog.GetString ("Data final:       ");
			this.hbox5.Add (this.lblEndDate);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblEndDate]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entryEndDate = new global::Gtk.Entry ();
			this.entryEndDate.CanFocus = true;
			this.entryEndDate.Name = "entryEndDate";
			this.entryEndDate.IsEditable = true;
			this.entryEndDate.InvisibleChar = '●';
			this.hbox5.Add (this.entryEndDate);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entryEndDate]));
			w11.Position = 1;
			this.vbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w14.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox9.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vseparator1]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.lblBank = new global::Gtk.Label ();
			this.lblBank.Name = "lblBank";
			this.lblBank.LabelProp = global::Mono.Unix.Catalog.GetString ("Número do Banco:");
			this.hbox10.Add (this.lblBank);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.lblBank]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.entryBankNum = new global::Gtk.Entry ();
			this.entryBankNum.CanFocus = true;
			this.entryBankNum.Name = "entryBankNum";
			this.entryBankNum.IsEditable = true;
			this.entryBankNum.InvisibleChar = '●';
			this.hbox10.Add (this.entryBankNum);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.entryBankNum]));
			w17.Position = 1;
			this.vbox7.Add (this.hbox10);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox10]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.lblBranchNum = new global::Gtk.Label ();
			this.lblBranchNum.Name = "lblBranchNum";
			this.lblBranchNum.LabelProp = global::Mono.Unix.Catalog.GetString ("Número da Agência");
			this.hbox11.Add (this.lblBranchNum);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.lblBranchNum]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.entryBranchNum = new global::Gtk.Entry ();
			this.entryBranchNum.CanFocus = true;
			this.entryBranchNum.Name = "entryBranchNum";
			this.entryBranchNum.IsEditable = true;
			this.entryBranchNum.InvisibleChar = '●';
			this.hbox11.Add (this.entryBranchNum);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.entryBranchNum]));
			w20.Position = 1;
			this.vbox7.Add (this.hbox11);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox11]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.radioBtnCashed = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Compensado"));
			this.radioBtnCashed.CanFocus = true;
			this.radioBtnCashed.Name = "radioBtnCashed";
			this.radioBtnCashed.DrawIndicator = true;
			this.radioBtnCashed.UseUnderline = true;
			this.radioBtnCashed.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox13.Add (this.radioBtnCashed);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.radioBtnCashed]));
			w22.Position = 0;
			// Container child hbox13.Gtk.Box+BoxChild
			this.radioBtnReturned = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Retornado"));
			this.radioBtnReturned.CanFocus = true;
			this.radioBtnReturned.Name = "radioBtnReturned";
			this.radioBtnReturned.DrawIndicator = true;
			this.radioBtnReturned.UseUnderline = true;
			this.radioBtnReturned.Group = this.radioBtnCashed.Group;
			this.hbox13.Add (this.radioBtnReturned);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.radioBtnReturned]));
			w23.Position = 1;
			// Container child hbox13.Gtk.Box+BoxChild
			this.radioBtnAll = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Todos"));
			this.radioBtnAll.CanFocus = true;
			this.radioBtnAll.Name = "radioBtnAll";
			this.radioBtnAll.DrawIndicator = true;
			this.radioBtnAll.UseUnderline = true;
			this.radioBtnAll.Group = this.radioBtnCashed.Group;
			this.hbox13.Add (this.radioBtnAll);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.radioBtnAll]));
			w24.Position = 2;
			this.vbox7.Add (this.hbox13);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox13]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox9.Add (this.vbox7);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox7]));
			w26.Position = 1;
			this.hbox1.Add (this.hbox9);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox9]));
			w27.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview = new global::Gtk.TreeView ();
			this.treeview.CanFocus = true;
			this.treeview.Name = "treeview";
			this.GtkScrolledWindow.Add (this.treeview);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w30.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblTotal = new global::Gtk.Label ();
			this.lblTotal.Name = "lblTotal";
			this.lblTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total: R$ 0,00");
			this.vbox2.Add (this.lblTotal);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblTotal]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
