// -------------------------------------------------------------------------
// Cheque - An Application to help you keep track of checks in your custody
// Copyright (C) 2013 Rene Octavio Queiroz Dias
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Source code at <https://github.com/reneoctavio/Cheque>.
// -------------------------------------------------------------------------

// This file has been generated by the GUI designer. Do not modify.
namespace Cheque.GTK.Dialogs
{
	public partial class ChangePassword
	{
		private global::Gtk.Label lblMessage1;
		private global::Gtk.Entry entryOldPasswd;
		private global::Gtk.Label lblMessage2;
		private global::Gtk.Entry entryNewPasswd1;
		private global::Gtk.Label lblMessage3;
		private global::Gtk.Entry entryNewPasswd2;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Cheque.GTK.Dialogs.ChangePassword
			this.Name = "Cheque.GTK.Dialogs.ChangePassword";
			this.Title = global::Mono.Unix.Catalog.GetString ("Modificar Senha");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Internal child Cheque.GTK.Dialogs.ChangePassword.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.lblMessage1 = new global::Gtk.Label ();
			this.lblMessage1.Name = "lblMessage1";
			this.lblMessage1.LabelProp = global::Mono.Unix.Catalog.GetString ("Entre com sua antiga senha:");
			w1.Add (this.lblMessage1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.lblMessage1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.entryOldPasswd = new global::Gtk.Entry ();
			this.entryOldPasswd.CanFocus = true;
			this.entryOldPasswd.Name = "entryOldPasswd";
			this.entryOldPasswd.IsEditable = true;
			this.entryOldPasswd.InvisibleChar = '●';
			w1.Add (this.entryOldPasswd);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1 [this.entryOldPasswd]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.lblMessage2 = new global::Gtk.Label ();
			this.lblMessage2.Name = "lblMessage2";
			this.lblMessage2.LabelProp = global::Mono.Unix.Catalog.GetString ("Entre com sua nova senha:");
			w1.Add (this.lblMessage2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.lblMessage2]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.entryNewPasswd1 = new global::Gtk.Entry ();
			this.entryNewPasswd1.CanFocus = true;
			this.entryNewPasswd1.Name = "entryNewPasswd1";
			this.entryNewPasswd1.IsEditable = true;
			this.entryNewPasswd1.InvisibleChar = '●';
			w1.Add (this.entryNewPasswd1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.entryNewPasswd1]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.lblMessage3 = new global::Gtk.Label ();
			this.lblMessage3.Name = "lblMessage3";
			this.lblMessage3.LabelProp = global::Mono.Unix.Catalog.GetString ("Digite de novo sua nova senha:");
			w1.Add (this.lblMessage3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.lblMessage3]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.entryNewPasswd2 = new global::Gtk.Entry ();
			this.entryNewPasswd2.CanFocus = true;
			this.entryNewPasswd2.Name = "entryNewPasswd2";
			this.entryNewPasswd2.IsEditable = true;
			this.entryNewPasswd2.InvisibleChar = '●';
			w1.Add (this.entryNewPasswd2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.entryNewPasswd2]));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			// Internal child Cheque.GTK.Dialogs.ChangePassword.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "dialog1_ActionArea";
			w8.Spacing = 10;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.buttonCancel]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.buttonOk]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 168;
			this.Show ();
			this.entryOldPasswd.TextDeleted += new global::Gtk.TextDeletedHandler (this.OnEntryOldPasswdTextDeleted);
			this.entryOldPasswd.TextInserted += new global::Gtk.TextInsertedHandler (this.OnEntryOldPasswdTextInserted);
			this.entryNewPasswd2.TextDeleted += new global::Gtk.TextDeletedHandler (this.OnEntryNewPasswd2TextDeleted);
			this.entryNewPasswd2.TextInserted += new global::Gtk.TextInsertedHandler (this.OnEntryNewPasswd2TextInserted);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
