// -------------------------------------------------------------------------
// Cheque - An Application to help you keep track of checks in your custody
// Copyright (C) 2013 Rene Octavio Queiroz Dias
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Source code at <https://github.com/reneoctavio/Cheque>.
// -------------------------------------------------------------------------

// This file has been generated by the GUI designer. Do not modify.
namespace Cheque.GTK
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action AddAction;
		private global::Gtk.Action CheckAction;
		private global::Gtk.Action CustomerAction;
		private global::Gtk.Action Action;
		private global::Gtk.Action ReportsAction;
		private global::Gtk.Action ChecksAction;
		private global::Gtk.Action ModifyAction;
		private global::Gtk.Action PasswordAction;
		private global::Gtk.VBox containerVbox;
		private global::Gtk.MenuBar menubar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Cheque.GTK.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.AddAction = new global::Gtk.Action ("AddAction", global::Mono.Unix.Catalog.GetString ("Adicionar"), null, null);
			this.AddAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Adicionar");
			w1.Add (this.AddAction, null);
			this.CheckAction = new global::Gtk.Action ("CheckAction", global::Mono.Unix.Catalog.GetString ("Cheque"), null, null);
			this.CheckAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cheque");
			w1.Add (this.CheckAction, null);
			this.CustomerAction = new global::Gtk.Action ("CustomerAction", global::Mono.Unix.Catalog.GetString ("Cliente"), null, null);
			this.CustomerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cliente");
			w1.Add (this.CustomerAction, null);
			this.Action = new global::Gtk.Action ("Action", null, null, null);
			w1.Add (this.Action, null);
			this.ReportsAction = new global::Gtk.Action ("ReportsAction", global::Mono.Unix.Catalog.GetString ("Relatórios"), null, null);
			this.ReportsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Relatórios");
			w1.Add (this.ReportsAction, null);
			this.ChecksAction = new global::Gtk.Action ("ChecksAction", global::Mono.Unix.Catalog.GetString ("Cheques"), null, null);
			this.ChecksAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cheques");
			w1.Add (this.ChecksAction, null);
			this.ModifyAction = new global::Gtk.Action ("ModifyAction", global::Mono.Unix.Catalog.GetString ("Alterar"), null, null);
			this.ModifyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Alterar");
			w1.Add (this.ModifyAction, null);
			this.PasswordAction = new global::Gtk.Action ("PasswordAction", global::Mono.Unix.Catalog.GetString ("Senha"), null, null);
			this.PasswordAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Senha");
			w1.Add (this.PasswordAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Cheque.GTK.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Cheques");
			this.DefaultWidth = 1024;
			this.DefaultHeight = 768;
			// Container child Cheque.GTK.MainWindow.Gtk.Container+ContainerChild
			this.containerVbox = new global::Gtk.VBox ();
			this.containerVbox.Name = "containerVbox";
			this.containerVbox.Spacing = 6;
			// Container child containerVbox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar'><menu name='AddAction' action='AddAction'><menuitem name='CheckAction' action='CheckAction'/><menuitem name='CustomerAction' action='CustomerAction'/></menu><menu name='ReportsAction' action='ReportsAction'><menuitem name='ChecksAction' action='ChecksAction'/></menu><menu name='ModifyAction' action='ModifyAction'><menuitem name='PasswordAction' action='PasswordAction'/></menu></menubar></ui>");
			this.menubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar")));
			this.menubar.Name = "menubar";
			this.containerVbox.Add (this.menubar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.containerVbox [this.menubar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.containerVbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.CheckAction.Activated += new global::System.EventHandler (this.OnCheckActionActivated);
			this.CustomerAction.Activated += new global::System.EventHandler (this.OnCustomerActionActivated);
			this.ChecksAction.Activated += new global::System.EventHandler (this.OnChecksActionActivated);
			this.PasswordAction.Activated += new global::System.EventHandler (this.OnPasswordActionActivated);
		}
	}
}
