
// This file has been generated by the GUI designer. Do not modify.
namespace Cheque.GTK.Screens
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action AddAction;
		private global::Gtk.Action BankAction;
		private global::Gtk.Action CheckAction;
		private global::Gtk.Action CustomerAction;
		private global::Gtk.Action UpdateAction;
		private global::Gtk.Action RemoveAction;
		private global::Gtk.Action Action;
		private global::Gtk.Action ReportsAction;
		private global::Gtk.Action ChecksAction;
		private global::Gtk.VBox containerVbox;
		private global::Gtk.MenuBar menubar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Cheque.GTK.Screens.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.AddAction = new global::Gtk.Action ("AddAction", global::Mono.Unix.Catalog.GetString ("Adicionar"), null, null);
			this.AddAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Adicionar");
			w1.Add (this.AddAction, null);
			this.BankAction = new global::Gtk.Action ("BankAction", global::Mono.Unix.Catalog.GetString ("Banco"), null, null);
			this.BankAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Banco");
			w1.Add (this.BankAction, null);
			this.CheckAction = new global::Gtk.Action ("CheckAction", global::Mono.Unix.Catalog.GetString ("Cheque"), null, null);
			this.CheckAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cheque");
			w1.Add (this.CheckAction, null);
			this.CustomerAction = new global::Gtk.Action ("CustomerAction", global::Mono.Unix.Catalog.GetString ("Cliente"), null, null);
			this.CustomerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cliente");
			w1.Add (this.CustomerAction, null);
			this.UpdateAction = new global::Gtk.Action ("UpdateAction", global::Mono.Unix.Catalog.GetString ("Atualizar"), null, null);
			this.UpdateAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Atualizar");
			w1.Add (this.UpdateAction, null);
			this.RemoveAction = new global::Gtk.Action ("RemoveAction", global::Mono.Unix.Catalog.GetString ("Remover"), null, null);
			this.RemoveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Remover");
			w1.Add (this.RemoveAction, null);
			this.Action = new global::Gtk.Action ("Action", null, null, null);
			w1.Add (this.Action, null);
			this.ReportsAction = new global::Gtk.Action ("ReportsAction", global::Mono.Unix.Catalog.GetString ("Relatórios"), null, null);
			this.ReportsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Relatórios");
			w1.Add (this.ReportsAction, null);
			this.ChecksAction = new global::Gtk.Action ("ChecksAction", global::Mono.Unix.Catalog.GetString ("Cheques"), null, null);
			this.ChecksAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cheques");
			w1.Add (this.ChecksAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Cheque.GTK.Screens.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Cheques");
			this.DefaultWidth = 1024;
			this.DefaultHeight = 768;
			// Container child Cheque.GTK.Screens.MainWindow.Gtk.Container+ContainerChild
			this.containerVbox = new global::Gtk.VBox ();
			this.containerVbox.Name = "containerVbox";
			this.containerVbox.Spacing = 6;
			// Container child containerVbox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar'><menu name='AddAction' action='AddAction'><menuitem name='BankAction' action='BankAction'/><menuitem name='CheckAction' action='CheckAction'/><menuitem name='CustomerAction' action='CustomerAction'/></menu><menu name='UpdateAction' action='UpdateAction'/><menu name='RemoveAction' action='RemoveAction'/><menu name='ReportsAction' action='ReportsAction'><menuitem name='ChecksAction' action='ChecksAction'/></menu></menubar></ui>");
			this.menubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar")));
			this.menubar.Name = "menubar";
			this.containerVbox.Add (this.menubar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.containerVbox [this.menubar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.Add (this.containerVbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.BankAction.Activated += new global::System.EventHandler (this.OnBankActionActivated);
			this.CheckAction.Activated += new global::System.EventHandler (this.OnCheckActionActivated);
			this.CustomerAction.Activated += new global::System.EventHandler (this.OnCustomerActionActivated);
			this.ChecksAction.Activated += new global::System.EventHandler (this.OnChecksActionActivated);
		}
	}
}
