// -------------------------------------------------------------------------
// Cheque - An Application to help you keep track of checks in your custody
// Copyright (C) 2013 Rene Octavio Queiroz Dias
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Source code at <https://github.com/reneoctavio/Cheque>.
// -------------------------------------------------------------------------

// This file has been generated by the GUI designer. Do not modify.
namespace Cheque.GTK.Dialogs
{
	public partial class AddPassword
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label lblMessage;
		private global::Gtk.Entry entryPasswd;
		private global::Gtk.Label lblTypeAgain;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Entry entryPasswdAgain;
		private global::Gtk.CheckButton checkBtnSamePass;
		private global::Gtk.Button btnAccept;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Cheque.GTK.Dialogs.AddPassword
			this.Name = "Cheque.GTK.Dialogs.AddPassword";
			this.Title = global::Mono.Unix.Catalog.GetString ("Criar senha");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child Cheque.GTK.Dialogs.AddPassword.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblMessage = new global::Gtk.Label ();
			this.lblMessage.Name = "lblMessage";
			this.lblMessage.LabelProp = global::Mono.Unix.Catalog.GetString ("Digite sua nova senha abaixo:");
			this.vbox2.Add (this.lblMessage);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblMessage]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.entryPasswd = new global::Gtk.Entry ();
			this.entryPasswd.CanFocus = true;
			this.entryPasswd.Name = "entryPasswd";
			this.entryPasswd.IsEditable = true;
			this.entryPasswd.InvisibleChar = '●';
			this.vbox2.Add (this.entryPasswd);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entryPasswd]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblTypeAgain = new global::Gtk.Label ();
			this.lblTypeAgain.Name = "lblTypeAgain";
			this.lblTypeAgain.LabelProp = global::Mono.Unix.Catalog.GetString ("Digite sua senha novamente:");
			this.vbox2.Add (this.lblTypeAgain);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblTypeAgain]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryPasswdAgain = new global::Gtk.Entry ();
			this.entryPasswdAgain.CanFocus = true;
			this.entryPasswdAgain.Name = "entryPasswdAgain";
			this.entryPasswdAgain.IsEditable = true;
			this.entryPasswdAgain.InvisibleChar = '●';
			this.hbox1.Add (this.entryPasswdAgain);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entryPasswdAgain]));
			w4.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.checkBtnSamePass = new global::Gtk.CheckButton ();
			this.checkBtnSamePass.Sensitive = false;
			this.checkBtnSamePass.CanFocus = true;
			this.checkBtnSamePass.Name = "checkBtnSamePass";
			this.checkBtnSamePass.Label = global::Mono.Unix.Catalog.GetString ("Iguais");
			this.checkBtnSamePass.DrawIndicator = true;
			this.checkBtnSamePass.UseUnderline = true;
			this.hbox1.Add (this.checkBtnSamePass);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkBtnSamePass]));
			w5.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnAccept = new global::Gtk.Button ();
			this.btnAccept.Sensitive = false;
			this.btnAccept.CanFocus = true;
			this.btnAccept.Name = "btnAccept";
			this.btnAccept.UseUnderline = true;
			this.btnAccept.Label = global::Mono.Unix.Catalog.GetString ("Adicionar");
			this.vbox2.Add (this.btnAccept);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.btnAccept]));
			w7.Position = 4;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 136;
			this.Show ();
			this.entryPasswdAgain.TextDeleted += new global::Gtk.TextDeletedHandler (this.OnEntryPasswdAgainTextDeleted);
			this.entryPasswdAgain.TextInserted += new global::Gtk.TextInsertedHandler (this.OnEntryPasswdAgainTextInserted);
			this.btnAccept.Clicked += new global::System.EventHandler (this.OnBtnAcceptClicked);
		}
	}
}
