
// This file has been generated by the GUI designer. Do not modify.
namespace Cheque.GTK.Dialogs
{
	public partial class CheckNotebook
	{
		private global::Gtk.Notebook notebook1;
		private global::Cheque.GTK.Dialogs.NotebookPage.CheckInfo checkinfo;
		private global::Gtk.Label lblCheck;
		private global::Cheque.GTK.Dialogs.NotebookPage.CustomerInfo customerinfo1;
		private global::Gtk.Label lblCustomer;
		private global::Cheque.GTK.Dialogs.NotebookPage.BranchInfo branchinfo1;
		private global::Gtk.Label lblBranch1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Cheque.GTK.Dialogs.CheckNotebook
			this.Name = "Cheque.GTK.Dialogs.CheckNotebook";
			this.Title = global::Mono.Unix.Catalog.GetString ("Propiedades do Cheque");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child Cheque.GTK.Dialogs.CheckNotebook.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.CurrentPage = 2;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.checkinfo = new global::Cheque.GTK.Dialogs.NotebookPage.CheckInfo ();
			this.checkinfo.Events = ((global::Gdk.EventMask)(256));
			this.checkinfo.Name = "checkinfo";
			this.notebook1.Add (this.checkinfo);
			// Notebook tab
			this.lblCheck = new global::Gtk.Label ();
			this.lblCheck.Name = "lblCheck";
			this.lblCheck.LabelProp = global::Mono.Unix.Catalog.GetString ("Cheque");
			this.notebook1.SetTabLabel (this.checkinfo, this.lblCheck);
			this.lblCheck.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.customerinfo1 = new global::Cheque.GTK.Dialogs.NotebookPage.CustomerInfo ();
			this.customerinfo1.Events = ((global::Gdk.EventMask)(256));
			this.customerinfo1.Name = "customerinfo1";
			this.notebook1.Add (this.customerinfo1);
			global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.customerinfo1]));
			w2.Position = 1;
			// Notebook tab
			this.lblCustomer = new global::Gtk.Label ();
			this.lblCustomer.Name = "lblCustomer";
			this.lblCustomer.LabelProp = global::Mono.Unix.Catalog.GetString ("Cliente");
			this.notebook1.SetTabLabel (this.customerinfo1, this.lblCustomer);
			this.lblCustomer.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.branchinfo1 = new global::Cheque.GTK.Dialogs.NotebookPage.BranchInfo ();
			this.branchinfo1.Events = ((global::Gdk.EventMask)(256));
			this.branchinfo1.Name = "branchinfo1";
			this.notebook1.Add (this.branchinfo1);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.branchinfo1]));
			w3.Position = 2;
			// Notebook tab
			this.lblBranch1 = new global::Gtk.Label ();
			this.lblBranch1.Name = "lblBranch1";
			this.lblBranch1.LabelProp = global::Mono.Unix.Catalog.GetString ("Agência");
			this.notebook1.SetTabLabel (this.branchinfo1, this.lblBranch1);
			this.lblBranch1.ShowAll ();
			this.Add (this.notebook1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 475;
			this.DefaultHeight = 352;
			this.Show ();
		}
	}
}
