
// This file has been generated by the GUI designer. Do not modify.
namespace Cheque.GTK.Screens
{
	public partial class CheckInfo
	{
		private global::Gtk.VBox vbox11;
		private global::Gtk.VBox vbox12;
		private global::Gtk.Label lblName;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label lbl_ID;
		private global::Gtk.Entry entryID;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label lblNumber;
		private global::Gtk.Entry entryNumber;
		private global::Gtk.VBox vbox13;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label lblBank;
		private global::Gtk.Entry entryBankNum;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label lblBranch;
		private global::Gtk.Entry entryBranch;
		private global::Gtk.VBox vbox15;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label lblSerial;
		private global::Gtk.Entry entrySerial;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Label lblDueDate;
		private global::Gtk.Entry entryDueDate;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label lblValue;
		private global::Gtk.Entry entryValue;
		private global::Gtk.VBox vbox14;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Label lblCashDate;
		private global::Gtk.Entry entryCashDate;
		private global::Gtk.HBox hbox10;
		private global::Gtk.CheckButton checkBtnCashed;
		private global::Gtk.CheckButton checkBtnOverdue;
		private global::Gtk.Label lblIssueDate;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Button btnEdit;
		private global::Gtk.Button btnSave;
		private global::Gtk.Button btnClose;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Cheque.GTK.Screens.CheckInfo
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Cheque.GTK.Screens.CheckInfo";
			// Container child Cheque.GTK.Screens.CheckInfo.Gtk.Container+ContainerChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.lblName = new global::Gtk.Label ();
			this.lblName.Name = "lblName";
			this.lblName.LabelProp = global::Mono.Unix.Catalog.GetString ("Nome");
			this.lblName.UseMarkup = true;
			this.vbox12.Add (this.lblName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.lblName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lbl_ID = new global::Gtk.Label ();
			this.lbl_ID.Name = "lbl_ID";
			this.lbl_ID.LabelProp = global::Mono.Unix.Catalog.GetString ("ID:");
			this.hbox2.Add (this.lbl_ID);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lbl_ID]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entryID = new global::Gtk.Entry ();
			this.entryID.CanFocus = true;
			this.entryID.Name = "entryID";
			this.entryID.IsEditable = false;
			this.entryID.InvisibleChar = '●';
			this.hbox2.Add (this.entryID);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entryID]));
			w3.Position = 1;
			this.vbox12.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblNumber = new global::Gtk.Label ();
			this.lblNumber.Name = "lblNumber";
			this.lblNumber.LabelProp = global::Mono.Unix.Catalog.GetString ("Número:");
			this.hbox3.Add (this.lblNumber);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblNumber]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entryNumber = new global::Gtk.Entry ();
			this.entryNumber.CanFocus = true;
			this.entryNumber.Name = "entryNumber";
			this.entryNumber.IsEditable = false;
			this.entryNumber.InvisibleChar = '●';
			this.hbox3.Add (this.entryNumber);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entryNumber]));
			w6.Position = 1;
			this.vbox12.Add (this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox3]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox11.Add (this.vbox12);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.vbox12]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblBank = new global::Gtk.Label ();
			this.lblBank.Name = "lblBank";
			this.lblBank.LabelProp = global::Mono.Unix.Catalog.GetString ("Banco:");
			this.hbox4.Add (this.lblBank);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblBank]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entryBankNum = new global::Gtk.Entry ();
			this.entryBankNum.CanFocus = true;
			this.entryBankNum.Name = "entryBankNum";
			this.entryBankNum.IsEditable = false;
			this.entryBankNum.InvisibleChar = '●';
			this.hbox4.Add (this.entryBankNum);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entryBankNum]));
			w10.Position = 1;
			this.vbox13.Add (this.hbox4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox4]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lblBranch = new global::Gtk.Label ();
			this.lblBranch.Name = "lblBranch";
			this.lblBranch.LabelProp = global::Mono.Unix.Catalog.GetString ("Agência:");
			this.hbox5.Add (this.lblBranch);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblBranch]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entryBranch = new global::Gtk.Entry ();
			this.entryBranch.CanFocus = true;
			this.entryBranch.Name = "entryBranch";
			this.entryBranch.IsEditable = false;
			this.entryBranch.InvisibleChar = '●';
			this.hbox5.Add (this.entryBranch);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entryBranch]));
			w13.Position = 1;
			this.vbox13.Add (this.hbox5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox5]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox ();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblSerial = new global::Gtk.Label ();
			this.lblSerial.Name = "lblSerial";
			this.lblSerial.LabelProp = global::Mono.Unix.Catalog.GetString ("Série:");
			this.hbox6.Add (this.lblSerial);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblSerial]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entrySerial = new global::Gtk.Entry ();
			this.entrySerial.CanFocus = true;
			this.entrySerial.Name = "entrySerial";
			this.entrySerial.IsEditable = false;
			this.entrySerial.InvisibleChar = '●';
			this.hbox6.Add (this.entrySerial);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entrySerial]));
			w16.Position = 1;
			this.vbox15.Add (this.hbox6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox6]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.lblDueDate = new global::Gtk.Label ();
			this.lblDueDate.Name = "lblDueDate";
			this.lblDueDate.LabelProp = global::Mono.Unix.Catalog.GetString ("Data de Vencimento:");
			this.hbox7.Add (this.lblDueDate);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.lblDueDate]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entryDueDate = new global::Gtk.Entry ();
			this.entryDueDate.CanFocus = true;
			this.entryDueDate.Name = "entryDueDate";
			this.entryDueDate.IsEditable = false;
			this.entryDueDate.InvisibleChar = '●';
			this.hbox7.Add (this.entryDueDate);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.entryDueDate]));
			w19.Position = 1;
			this.vbox15.Add (this.hbox7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox7]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.lblValue = new global::Gtk.Label ();
			this.lblValue.Name = "lblValue";
			this.lblValue.LabelProp = global::Mono.Unix.Catalog.GetString ("Valor:");
			this.hbox8.Add (this.lblValue);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.lblValue]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.entryValue = new global::Gtk.Entry ();
			this.entryValue.CanFocus = true;
			this.entryValue.Name = "entryValue";
			this.entryValue.IsEditable = false;
			this.entryValue.InvisibleChar = '●';
			this.hbox8.Add (this.entryValue);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.entryValue]));
			w22.Position = 1;
			this.vbox15.Add (this.hbox8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox8]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox13.Add (this.vbox15);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.vbox15]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox11.Add (this.vbox13);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.vbox13]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.lblCashDate = new global::Gtk.Label ();
			this.lblCashDate.Name = "lblCashDate";
			this.lblCashDate.LabelProp = global::Mono.Unix.Catalog.GetString ("Data de Compensação:");
			this.hbox9.Add (this.lblCashDate);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.lblCashDate]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.entryCashDate = new global::Gtk.Entry ();
			this.entryCashDate.CanFocus = true;
			this.entryCashDate.Name = "entryCashDate";
			this.entryCashDate.IsEditable = false;
			this.entryCashDate.InvisibleChar = '●';
			this.hbox9.Add (this.entryCashDate);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.entryCashDate]));
			w27.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.checkBtnCashed = new global::Gtk.CheckButton ();
			this.checkBtnCashed.Sensitive = false;
			this.checkBtnCashed.CanFocus = true;
			this.checkBtnCashed.Name = "checkBtnCashed";
			this.checkBtnCashed.Label = global::Mono.Unix.Catalog.GetString ("Pago");
			this.checkBtnCashed.DrawIndicator = true;
			this.checkBtnCashed.UseUnderline = true;
			this.hbox10.Add (this.checkBtnCashed);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.checkBtnCashed]));
			w28.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.checkBtnOverdue = new global::Gtk.CheckButton ();
			this.checkBtnOverdue.Sensitive = false;
			this.checkBtnOverdue.CanFocus = true;
			this.checkBtnOverdue.Name = "checkBtnOverdue";
			this.checkBtnOverdue.Label = global::Mono.Unix.Catalog.GetString ("Pago Atrasado");
			this.checkBtnOverdue.DrawIndicator = true;
			this.checkBtnOverdue.UseUnderline = true;
			this.hbox10.Add (this.checkBtnOverdue);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.checkBtnOverdue]));
			w29.Position = 1;
			this.hbox9.Add (this.hbox10);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.hbox10]));
			w30.Position = 2;
			this.vbox14.Add (this.hbox9);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox9]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.lblIssueDate = new global::Gtk.Label ();
			this.lblIssueDate.Name = "lblIssueDate";
			this.lblIssueDate.LabelProp = global::Mono.Unix.Catalog.GetString ("Data de Cadastro:");
			this.vbox14.Add (this.lblIssueDate);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.lblIssueDate]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.btnEdit = new global::Gtk.Button ();
			this.btnEdit.CanFocus = true;
			this.btnEdit.Name = "btnEdit";
			this.btnEdit.UseUnderline = true;
			this.btnEdit.Label = global::Mono.Unix.Catalog.GetString ("Editar");
			this.hbox11.Add (this.btnEdit);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.btnEdit]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.btnSave = new global::Gtk.Button ();
			this.btnSave.Sensitive = false;
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString ("Salvar");
			this.hbox11.Add (this.btnSave);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.btnSave]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.btnClose = new global::Gtk.Button ();
			this.btnClose.CanFocus = true;
			this.btnClose.Name = "btnClose";
			this.btnClose.UseUnderline = true;
			this.btnClose.Label = global::Mono.Unix.Catalog.GetString ("Fechar");
			this.hbox11.Add (this.btnClose);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.btnClose]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox14.Add (this.hbox11);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox11]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox11.Add (this.vbox14);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.vbox14]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			this.Add (this.vbox11);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.entryID.TextDeleted += new global::Gtk.TextDeletedHandler (this.OnEntryIDTextDeleted);
			this.entryID.TextInserted += new global::Gtk.TextInsertedHandler (this.OnEntryIDTextInserted);
			this.checkBtnCashed.Toggled += new global::System.EventHandler (this.OnCheckBtnCashedToggled);
			this.checkBtnOverdue.Toggled += new global::System.EventHandler (this.OnCheckBtnOverdueToggled);
			this.btnEdit.Clicked += new global::System.EventHandler (this.OnBtnEditClicked);
			this.btnSave.Clicked += new global::System.EventHandler (this.OnBtnSaveClicked);
			this.btnClose.Clicked += new global::System.EventHandler (this.OnBtnCloseClicked);
		}
	}
}
