// -------------------------------------------------------------------------
// Cheque - An Application to help you keep track of checks in your custody
// Copyright (C) 2013 Rene Octavio Queiroz Dias
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Source code at <https://github.com/reneoctavio/Cheque>.
// -------------------------------------------------------------------------

// This file has been generated by the GUI designer. Do not modify.
namespace Cheque.GTK.Tables
{
	public partial class ReportCheckTable
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label lblName;
		private global::Gtk.Entry entryName;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label lblTypeId;
		private global::Gtk.Entry entryID;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label lblStartDate;
		private global::Gtk.Entry entryStartDate;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Label lblEndDate;
		private global::Gtk.Entry entryEndDate;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label lblBank;
		private global::Gtk.Entry entryBankNum;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Label lblBranchNum;
		private global::Gtk.Entry entryBranchNum;
		private global::Gtk.HBox hbox12;
		private global::Gtk.VBox vbox5;
		private global::Gtk.RadioButton radioBtnAll;
		private global::Gtk.RadioButton radioBtnReturned;
		private global::Gtk.VSeparator vseparator2;
		private global::Gtk.VBox vbox6;
		private global::Gtk.RadioButton radioBtnCashed;
		private global::Gtk.RadioButton radioBtnNotPastDate;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Cheque.GTK.Tables.CheckTableView checktableview;
		private global::Gtk.Label lblTotal;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Cheque.GTK.Tables.ReportCheckTable
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Cheque.GTK.Tables.ReportCheckTable";
			// Container child Cheque.GTK.Tables.ReportCheckTable.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblName = new global::Gtk.Label ();
			this.lblName.Name = "lblName";
			this.lblName.LabelProp = global::Mono.Unix.Catalog.GetString ("Nome:");
			this.hbox4.Add (this.lblName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entryName = new global::Gtk.Entry ();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.IsEditable = true;
			this.entryName.InvisibleChar = '●';
			this.hbox4.Add (this.entryName);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entryName]));
			w2.Position = 1;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblTypeId = new global::Gtk.Label ();
			this.lblTypeId.Name = "lblTypeId";
			this.lblTypeId.LabelProp = global::Mono.Unix.Catalog.GetString ("CPF/CNPJ:");
			this.hbox6.Add (this.lblTypeId);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblTypeId]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryID = new global::Gtk.Entry ();
			this.entryID.CanFocus = true;
			this.entryID.Name = "entryID";
			this.entryID.IsEditable = true;
			this.entryID.InvisibleChar = '●';
			this.hbox6.Add (this.entryID);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.entryID]));
			w5.Position = 1;
			this.vbox3.Add (this.hbox6);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.lblStartDate = new global::Gtk.Label ();
			this.lblStartDate.Name = "lblStartDate";
			this.lblStartDate.LabelProp = global::Mono.Unix.Catalog.GetString ("Data de início:");
			this.hbox8.Add (this.lblStartDate);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.lblStartDate]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.entryStartDate = new global::Gtk.Entry ();
			this.entryStartDate.CanFocus = true;
			this.entryStartDate.Name = "entryStartDate";
			this.entryStartDate.IsEditable = true;
			this.entryStartDate.InvisibleChar = '●';
			this.hbox8.Add (this.entryStartDate);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.entryStartDate]));
			w8.Position = 1;
			this.vbox3.Add (this.hbox8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox8]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.lblEndDate = new global::Gtk.Label ();
			this.lblEndDate.Name = "lblEndDate";
			this.lblEndDate.LabelProp = global::Mono.Unix.Catalog.GetString ("Data final:");
			this.hbox9.Add (this.lblEndDate);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.lblEndDate]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.entryEndDate = new global::Gtk.Entry ();
			this.entryEndDate.CanFocus = true;
			this.entryEndDate.Name = "entryEndDate";
			this.entryEndDate.IsEditable = true;
			this.entryEndDate.InvisibleChar = '●';
			this.hbox9.Add (this.entryEndDate);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.entryEndDate]));
			w11.Position = 1;
			this.vbox3.Add (this.hbox9);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox9]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w13.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox1.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator1]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lblBank = new global::Gtk.Label ();
			this.lblBank.Name = "lblBank";
			this.lblBank.LabelProp = global::Mono.Unix.Catalog.GetString ("Número do Banco:");
			this.hbox5.Add (this.lblBank);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblBank]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entryBankNum = new global::Gtk.Entry ();
			this.entryBankNum.CanFocus = true;
			this.entryBankNum.Name = "entryBankNum";
			this.entryBankNum.IsEditable = true;
			this.entryBankNum.InvisibleChar = '●';
			this.hbox5.Add (this.entryBankNum);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entryBankNum]));
			w16.Position = 1;
			this.vbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.lblBranchNum = new global::Gtk.Label ();
			this.lblBranchNum.Name = "lblBranchNum";
			this.lblBranchNum.LabelProp = global::Mono.Unix.Catalog.GetString ("Número da Agência:");
			this.hbox7.Add (this.lblBranchNum);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.lblBranchNum]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entryBranchNum = new global::Gtk.Entry ();
			this.entryBranchNum.CanFocus = true;
			this.entryBranchNum.Name = "entryBranchNum";
			this.entryBranchNum.IsEditable = true;
			this.entryBranchNum.InvisibleChar = '●';
			this.hbox7.Add (this.entryBranchNum);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.entryBranchNum]));
			w19.Position = 1;
			this.vbox4.Add (this.hbox7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox7]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.radioBtnAll = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Todos"));
			this.radioBtnAll.CanFocus = true;
			this.radioBtnAll.Name = "radioBtnAll";
			this.radioBtnAll.Active = true;
			this.radioBtnAll.DrawIndicator = true;
			this.radioBtnAll.UseUnderline = true;
			this.radioBtnAll.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox5.Add (this.radioBtnAll);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.radioBtnAll]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.radioBtnReturned = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Retornados"));
			this.radioBtnReturned.CanFocus = true;
			this.radioBtnReturned.Name = "radioBtnReturned";
			this.radioBtnReturned.DrawIndicator = true;
			this.radioBtnReturned.UseUnderline = true;
			this.radioBtnReturned.Group = this.radioBtnAll.Group;
			this.vbox5.Add (this.radioBtnReturned);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.radioBtnReturned]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.hbox12.Add (this.vbox5);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.vbox5]));
			w23.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.hbox12.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.vseparator2]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.radioBtnCashed = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Compensados"));
			this.radioBtnCashed.CanFocus = true;
			this.radioBtnCashed.Name = "radioBtnCashed";
			this.radioBtnCashed.DrawIndicator = true;
			this.radioBtnCashed.UseUnderline = true;
			this.radioBtnCashed.Group = this.radioBtnAll.Group;
			this.vbox6.Add (this.radioBtnCashed);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.radioBtnCashed]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.radioBtnNotPastDate = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("A vencer"));
			this.radioBtnNotPastDate.CanFocus = true;
			this.radioBtnNotPastDate.Name = "radioBtnNotPastDate";
			this.radioBtnNotPastDate.DrawIndicator = true;
			this.radioBtnNotPastDate.UseUnderline = true;
			this.radioBtnNotPastDate.Group = this.radioBtnAll.Group;
			this.vbox6.Add (this.radioBtnNotPastDate);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.radioBtnNotPastDate]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.hbox12.Add (this.vbox6);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.vbox6]));
			w27.Position = 2;
			this.vbox4.Add (this.hbox12);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox12]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.hbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
			w29.Position = 2;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.checktableview = new global::Cheque.GTK.Tables.CheckTableView ();
			this.checktableview.CanFocus = true;
			this.checktableview.Name = "checktableview";
			this.GtkScrolledWindow.Add (this.checktableview);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w32.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblTotal = new global::Gtk.Label ();
			this.lblTotal.Name = "lblTotal";
			this.lblTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total: R$ 0,00");
			this.vbox2.Add (this.lblTotal);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblTotal]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
